# frozen_string_literal: true

=begin
#Telstra Messaging API

OpenAPI spec version: 2.2.9

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.2.0

=end

require 'test_helper'

class ApiClientTest < Minitest::Test
  describe 'initialization' do
    describe 'URL stuff' do
      describe 'host' do
        it 'removes http from host' do
          Telstra_Messaging.configure { |c| c.host = 'http://example.com' }
          assert_equal 'example.com', Telstra_Messaging::Configuration.default.host
        end

        it 'removes https from host' do
          Telstra_Messaging.configure { |c| c.host = 'https://wookiee.com' }
          assert_equal 'wookiee.com', Telstra_Messaging::ApiClient.default.config.host
        end

        it 'removes trailing path from host' do
          Telstra_Messaging.configure { |c| c.host = 'hobo.com/v4' }
          assert_equal 'hobo.com', Telstra_Messaging::Configuration.default.host
        end
      end

      describe 'base_path' do
        it "prepends a slash to base_path" do
          Telstra_Messaging.configure { |c| c.base_path = 'v4/dog' }
          assert_equal '/v4/dog', Telstra_Messaging::Configuration.default.base_path
        end

        it "doesn't prepend a slash if one is already there" do
          Telstra_Messaging.configure { |c| c.base_path = '/v4/dog' }
          assert_equal '/v4/dog', Telstra_Messaging::Configuration.default.base_path
        end

        it "ends up as a blank string if nil" do
          Telstra_Messaging.configure { |c| c.base_path = nil }
          assert_equal '', Telstra_Messaging::Configuration.default.base_path
        end
      end
    end
  end

  describe 'params_encoding in #build_request' do
    def setup
      @config = Telstra_Messaging::Configuration.new
      @api_client = Telstra_Messaging::ApiClient.new(@config)
    end

    it 'defaults to nil' do
      assert_nil Telstra_Messaging::Configuration.default.params_encoding
      assert_nil @config.params_encoding

      request = @api_client.build_request(:get, '/test')
      assert_nil request.options[:params_encoding]
    end

    it 'can be customized' do
      @config.params_encoding = :multi
      request = @api_client.build_request(:get, '/test')
      assert_equal :multi, request.options[:params_encoding]
    end
  end

  describe 'timeout in #build_request' do
    def setup
      @config = Telstra_Messaging::Configuration.new
      @api_client = Telstra_Messaging::ApiClient.new(@config)
    end

    it 'defaults to 0' do
      assert_equal 0, Telstra_Messaging::Configuration.default.timeout
      assert_equal 0, @config.timeout

      request = @api_client.build_request(:get, '/test')
      assert_equal 0, request.options[:timeout]
    end

    it 'can be customized' do
      @config.timeout = 100
      request = @api_client.build_request(:get, '/test')
      assert_equal 100, request.options[:timeout]
    end
  end

  describe '#deserialize' do
    def setup
      @api_client = Telstra_Messaging::ApiClient.new
    end

    it "handles Array<Integer>" do
      headers = { 'Content-Type' => 'application/json' }
      response = Minitest::Mock.new
      response.expect :headers, headers
      response.expect :body, '[12, 34]'
      
      data = @api_client.deserialize(response, 'Array<Integer>')
      assert_instance_of Array, data
      assert_equal [12, 34], data
      
      response.verify
    end

    it 'handles Array<Array<Integer>>' do
      headers = { 'Content-Type' => 'application/json' }
      response = Minitest::Mock.new
      response.expect :headers, headers
      response.expect :body, '[[12, 34], [56]]'
      
      data = @api_client.deserialize(response, 'Array<Array<Integer>>')
      assert_instance_of Array, data
      assert_equal [[12, 34], [56]], data
      
      response.verify
    end

    it 'handles Hash<String, String>' do
      headers = { 'Content-Type' => 'application/json' }
      response = Minitest::Mock.new
      response.expect :headers, headers
      response.expect :body, '{"message": "Hello"}'
      
      data = @api_client.deserialize(response, 'Hash<String, String>')
      assert_instance_of Hash, data
      assert_equal({ :message => 'Hello' }, data)
      
      response.verify
    end
  end

  describe "#object_to_hash" do
    it 'ignores nils and includes empty arrays' do
      # uncomment below to test object_to_hash for model
      # api_client = Telstra_Messaging::ApiClient.new
      # _model = Telstra_Messaging::ModelName.new
      # update the model attribute below
      # _model.id = 1
      # update the expected value (hash) below
      # expected = {id: 1, name: '', tags: []}
      # assert_equal expected, api_client.object_to_hash(_model)
    end
  end

  describe '#build_collection_param' do
    def setup
      @param = ['aa', 'bb', 'cc']
      @api_client = Telstra_Messaging::ApiClient.new
    end

    it 'works for csv' do
      assert_equal 'aa,bb,cc', @api_client.build_collection_param(@param, :csv)
    end

    it 'works for ssv' do
      assert_equal 'aa bb cc', @api_client.build_collection_param(@param, :ssv)
    end

    it 'works for tsv' do
      assert_equal "aa\tbb\tcc", @api_client.build_collection_param(@param, :tsv)
    end

    it 'works for pipes' do
      assert_equal 'aa|bb|cc', @api_client.build_collection_param(@param, :pipes)
    end

    it 'works for multi' do
      assert_equal ['aa', 'bb', 'cc'], @api_client.build_collection_param(@param, :multi)
    end

    it 'fails for invalid collection format' do
      assert_raises RuntimeError do
        @api_client.build_collection_param(@param, :INVALID)
      end
    end
  end

  describe '#json_mime?' do
    def setup
      @api_client = Telstra_Messaging::ApiClient.new
    end

    it 'works' do
      assert_equal false, @api_client.json_mime?(nil)
      assert_equal false, @api_client.json_mime?('')

      assert_equal true, @api_client.json_mime?('application/json')
      assert_equal true, @api_client.json_mime?('application/json; charset=UTF8')
      assert_equal true, @api_client.json_mime?('APPLICATION/JSON')

      assert_equal false, @api_client.json_mime?('application/xml')
      assert_equal false, @api_client.json_mime?('text/plain')
      assert_equal false, @api_client.json_mime?('application/jsonp')
    end
  end

  describe '#select_header_accept' do
    def setup
      @api_client = Telstra_Messaging::ApiClient.new
    end

    it 'works' do
      assert_nil @api_client.select_header_accept(nil)
      assert_nil @api_client.select_header_accept([])

      assert_equal 'application/json', @api_client.select_header_accept(['application/json'])
      assert_equal 'application/json; charset=UTF8', @api_client.select_header_accept(['application/xml', 'application/json; charset=UTF8'])
      assert_equal 'APPLICATION/JSON', @api_client.select_header_accept(['APPLICATION/JSON', 'text/html'])

      assert_equal 'application/xml', @api_client.select_header_accept(['application/xml'])
      assert_equal 'text/html,application/xml', @api_client.select_header_accept(['text/html', 'application/xml'])
    end
  end

  describe '#select_header_content_type' do
    def setup
      @api_client = Telstra_Messaging::ApiClient.new
    end

    it 'works' do
      assert_equal 'application/json', @api_client.select_header_content_type(nil)
      assert_equal 'application/json', @api_client.select_header_content_type([])

      assert_equal 'application/json', @api_client.select_header_content_type(['application/json'])
      assert_equal 'application/json; charset=UTF8', @api_client.select_header_content_type(['application/xml', 'application/json; charset=UTF8'])
      assert_equal 'APPLICATION/JSON', @api_client.select_header_content_type(['APPLICATION/JSON', 'text/html'])
      assert_equal 'application/xml', @api_client.select_header_content_type(['application/xml'])
      assert_equal 'text/plain', @api_client.select_header_content_type(['text/plain', 'application/xml'])
    end
  end

  describe '#sanitize_filename' do
    def setup
      @api_client = Telstra_Messaging::ApiClient.new
    end

    it 'works' do
      assert_equal 'sun', @api_client.sanitize_filename('sun')
      assert_equal 'sun.gif', @api_client.sanitize_filename('sun.gif')
      assert_equal 'sun.gif', @api_client.sanitize_filename('../sun.gif')
      assert_equal 'sun.gif', @api_client.sanitize_filename('/var/tmp/sun.gif')
      assert_equal 'sun.gif', @api_client.sanitize_filename('./sun.gif')
      assert_equal 'sun.gif', @api_client.sanitize_filename('..\sun.gif')
      assert_equal 'sun.gif', @api_client.sanitize_filename('\var\tmp\sun.gif')
      assert_equal 'sun.gif', @api_client.sanitize_filename('c:\var\tmp\sun.gif')
      assert_equal 'sun.gif', @api_client.sanitize_filename('.\sun.gif')
    end
  end
end
