# frozen_string_literal: true

=begin
#Telstra Messaging API

OpenAPI spec version: 2.2.9

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.2.0

=end

require 'test_helper'

class ConfigurationTest < Minitest::Test
  describe Telstra_Messaging::Configuration do
    def setup
      @config = Telstra_Messaging::Configuration.default
      # Reset configuration before each test
      # uncomment below to setup host and base_path
      # require 'URI'
      # uri = URI.parse("https://tapi.telstra.com/v2")
      # Telstra_Messaging.configure do |c|
      #   c.host = uri.host
      #   c.base_path = uri.path
      # end
    end

    describe '#base_url' do
      it 'should have the default value' do
        # uncomment below to test default value of the base path
        # assert_equal "https://tapi.telstra.com/v2", @config.base_url
      end

      it 'should remove trailing slashes' do
        [nil, '', '/', '//'].each do |base_path|
          @config.base_path = base_path
          # uncomment below to test trailing slashes
          # assert_equal "https://tapi.telstra.com/v2", @config.base_url
        end
      end
    end
  end
end
