# frozen_string_literal: true

=begin
#Telstra Messaging API

# # Introduction  Send and receive SMS and MMS messages globally using Telstra's enterprise grade Messaging API.

OpenAPI spec version: 2.2.9

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.2.0

=end

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'Telstra_Messaging'
require 'minitest/autorun'
require 'minitest/pride'

# Mock and stub support for testing
class Minitest::Test
  def setup
    # Reset configuration before each test
    Telstra_Messaging.configure do |config|
      config.host = 'localhost'
      config.base_path = ''
      config.scheme = 'http'
      config.api_key = {}
      config.api_key_prefix = {}
      config.username = nil
      config.password = nil
      config.access_token = nil
      config.debugging = false
      config.inject_format = false
      config.force_ending_format = false
      config.logger = Logger.new(STDOUT)
      config.logger.level = Logger::WARN
      config.params_encoding = nil
      config.timeout = 0
      config.ssl_ca_cert = nil
      config.cert_file = nil
      config.key_file = nil
      config.verify_ssl = true
      config.verify_ssl_host = true
    end
  end
end